### ISSUE TITLE
NameError: uninitialized constant ActiveRecord::ConnectionAdapters::ConnectionManagement

### ISSUE THREAD

**Issue by checkbutton** [jhollinger/otr-activerecord#1]
In AR 5, `use ActiveRecord::ConnectionAdapters::ConnectionManagement` causes this error. Removing the line seems to fix it. Do you see any problems with this?

**Comment by jhollinger** [comment]
Seems likely it will cause issues in production. I'll research and get back to you. It's possible they just changed the name of that middleware.

**Comment by jhollinger** [comment]
I can't find much on that except that it's been removed in 5. I guess go ahead and remove it and see what happens. My expectation is that your database connection pool will eventually become exhausted without some middleware like this, esp. if you use a threaded server like puma. But maybe they've added some magic to fix that w/o middleware. But if you start seeing exceptions like "unable to obtain a database connection," this is likely the cause. Let me know how it goes. I'll update the README accordingly.

**Comment by checkbutton** [comment]
This is what I found in the documentation:
> Simply use `ActiveRecord::Base.connection` as with Active Record 2.1 and earlier (pre-connection-pooling). Eventually, when you're done with the connection(s) and wish it to be returned to the pool, you call `ActiveRecord::Base.clear_active_connections!`. This will be the default behavior for Active Record when used in conjunction with Action Pack's request handling cycle.
This sounds to me like they removed the Rack Middleware, as the same behavior is included in their Action Pack request handling cycle. Sounds to me that it might break, if you don't a) use Action Pack for request handling or b) handle the connection clearing yourself in a middleware.

**Comment by jhollinger** [comment]
Sounds like we'll need to write replacement middleware for that. Shouldn't be too hard - here's what the old middleware looked like - https://github.com/rails/rails/blob/v4.2.7.1/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L645. It uses the MIT license, so copying it verbatim shouldn't be an issue. I'll have time later this week. But if you'd like to submit a PR that's cool too.

**Comment by jhollinger** [comment]
Just pushed up version 1.1.0. You can use `OTR::ActiveRecord::ConnectionManagement`.
