### ISSUE TITLE
Patch level update to 1.2.6 broke our stuff

### ISSUE THREAD

**Issue by graywolf-at-work** [jhollinger/otr-activerecord#11]
In our environment we have our own variable for controlling the environment (lets call it `XX_ENV`) and we are validating that either `RACK_ENV` does not exist or is same to the `XX_ENV`. Commit a9dbeba6455aa360246def73ab1df9f0a8120b2d broke that assumption since it sets `RACK_ENV` even when it's not set as env variable before running the process.

I'm not sure hard-setting env variable like this without a way to suppress it is nice but why was it done as patch level only change when it has a chance of breaking stuff (as it did).

Would it be possible to revert the change and release new major version since this is obviously breaking change?

Thanks for considering this.

**Comment by jhollinger** [comment]
Removing that will break some things for ActiveRecord 5.2 projects (it does some very stupid things w/r/t development environments). But I see your point. I will try to find another way of fixing that without clobbering RACK_ENV/RAILS_ENV.

**Comment by jhollinger** [comment]
Good news, I found an undocumented AR workaround to satisfy both requirements. v1.2.7 should be up soon. Sorry for the breakage.

**Comment by graywolf-at-work** [comment]
No problem, I really appreciate this speedy resolution. I'll give it try and if it fixes our problem (it should) I'll close this issue.

Thanks a lot ^_^

**Comment by graywolf-at-work** [comment]
1.2.7 works for us, thanks again for solving this that quickly :)
