### ISSUE TITLE
create_migration not working

### ISSUE THREAD

**Issue by shivamb** [jhollinger/otr-activerecord#37]
When trying to create a migration, getting like this:

```bash
bundle exec rake db:create_migration[create_widgets]

zsh: no matches found: db:create_migration[create_widgets]
```

**Comment by shivamb** [comment]
It worked when used the task name with quotes

```bash
bundle exec rake 'db:create_migration[create_widgets]'
```

**Comment by jhollinger** [comment]
Yes, in zsh `[]` has some special meaning (not sure what). You can either use quotes or escape them with `\`.
