### ISSUE TITLE
Is it possible to generate a structure.sql file?

### ISSUE THREAD

**Issue by marcomarcianesi** [jhollinger/otr-activerecord#56]
I have some db views, and I'd like to generate a `structure.sql` file instead of a `schema.rb`

Is it possible to do so at the moment?

**Comment by jhollinger** [comment]
Yes, but you actually don't need any help from OTR. Just put the following somewhere in your app's initialization area:

```ruby
ActiveRecord::Base.schema_format = :sql
```
