### ISSUE TITLE
migrations_paths being ignored

### ISSUE THREAD

**Issue by Papipo** [jhollinger/otr-activerecord#9]
I have setup OTR::ActiveRecord as expected, but I get this on my rakefile:

```ruby
puts "OTR: {OTR::ActiveRecord.migrations_paths.inspect}"
puts "AR: #{::ActiveRecord::Tasks::DatabaseTasks.migrations_paths}"
```

Resulting in:
```
OTR: ["/Users/papipo/Projects/mathtrades/backend/apps/auth/migrations"]
AR: ["db/migrate"]
```

Thus my migrations aren't run.

**Comment by jhollinger** [comment]
What version of ActiveRecord are you using?

**Comment by Papipo** [comment]
5.0.2

**Comment by jhollinger** [comment]
Hmm, I'm not able to duplicate. I tried in one of the example apps (https://github.com/jhollinger/otr-activerecord/tree/master/examples/grape-activerecord5). I changed the default migration paths in the `Rakefile` but everything seems to work.
